version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: "master"
    update_schedule: "weekly"
    default_reviewers:
    - "SonyaMoisset"
    default_assignees:
    - "SonyaMoisset"
    default_milestone: 9
    default_labels:
    - "Dependencies"
    - "Security"
    allowed_updates:
    - match:
        dependency_type: "development"
        update_type: "security"
    - match:
        dependency_type: "production"
        update_type: "all"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true