export { default as AccessibilityIcon } from './AccessibilityIcon'
export { default as GenderIcon } from './GenderIcon'
export { default as LaptopIcon } from './LaptopIcon'
export { default as MailIcon } from './mailIcon'
export { default as MapPinIcon } from './MapPinIcon'
export { default as OnDemandIcon } from './OnDemandIcon'
export { default as PhoneIcon } from './phoneIcon'
export { default as TicketIcon } from './ticketIcon'
